before:
  hooks:
    - go mod tidy
builds:
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
      - CC=gcc
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/Andriiklymiuk/ung/cmd.Version={{.Version}}
      - -X github.com/Andriiklymiuk/ung/cmd.GitCommit={{.Commit}}
      - -X github.com/Andriiklymiuk/ung/cmd.BuildDate={{.Date}}
  - id: linux-arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X github.com/Andriiklymiuk/ung/cmd.Version={{.Version}}
      - -X github.com/Andriiklymiuk/ung/cmd.GitCommit={{.Commit}}
      - -X github.com/Andriiklymiuk/ung/cmd.BuildDate={{.Date}}
  - id: darwin-amd64
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/Andriiklymiuk/ung/cmd.Version={{.Version}}
      - -X github.com/Andriiklymiuk/ung/cmd.GitCommit={{.Commit}}
      - -X github.com/Andriiklymiuk/ung/cmd.BuildDate={{.Date}}
  - id: darwin-arm64
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X github.com/Andriiklymiuk/ung/cmd.Version={{.Version}}
      - -X github.com/Andriiklymiuk/ung/cmd.GitCommit={{.Commit}}
      - -X github.com/Andriiklymiuk/ung/cmd.BuildDate={{.Date}}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
brews:
  - name: ung
    homepage: https://github.com/Andriiklymiuk/ung
    description: "Universal Next-Gen Billing & Tracking CLI - Manage invoices, clients, and time tracking"
    repository:
      owner: Andriiklymiuk
      name: homebrew-tools
      token: "{{ .Env.GH_PAT }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
